import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// Where the showcase fetches its screens from.
//
// The default is GitHub Raw, so a fresh clone renders all 17 screens with no backend to stand up.
// Pointing it at a local HeimUI Studio is one line in `local.properties`, which is not version
// controlled — which is the point: nobody can commit a `localhost` that resolves only on the
// machine that wrote it, and a release build never ships one either.
//
//   sdui.baseUrl=http://10.0.2.2:8080
//
// `-PsduiBaseUrl=...` overrides it for a single build, the way `-PheimuiCore` does for the SDK.
//
// Read through the provider API rather than by opening the file directly, so the configuration
// cache re-runs this when `local.properties` changes instead of serving a stale URL.
val sduiBaseUrl: Provider<String> =
    providers.gradleProperty("sduiBaseUrl")
        .orElse(
            providers.fileContents(rootProject.layout.projectDirectory.file("local.properties"))
                .asText
                .map { text -> Properties().apply { load(text.reader()) }.getProperty("sdui.baseUrl").orEmpty() }
                .filter { it.isNotBlank() }
        )
        .orElse("https://raw.githubusercontent.com/heimui-io/heimui-demo/main/sdui")

val generateDemoBuildConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/demoBuildConfig")
    val baseUrl = sduiBaseUrl
    inputs.property("sduiBaseUrl", baseUrl)
    outputs.dir(outputDir)
    doLast {
        val target = outputDir.get().file("io/heimui/demo/DemoBuildConfig.kt").asFile
        target.parentFile.mkdirs()
        target.writeText(
            """
            package io.heimui.demo

            // Generated by the `generateDemoBuildConfig` task in shared/build.gradle.kts. Do not edit.
            internal object DemoBuildConfig {
                const val SDUI_BASE_URL: String = "${baseUrl.get()}"
            }
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }
    
    android {
       namespace = "io.heimui.demo.shared"
       compileSdk = libs.versions.android.compileSdk.get().toInt()
       minSdk = libs.versions.android.minSdk.get().toInt()
    
       compilerOptions {
           jvmTarget = JvmTarget.JVM_11
       }
       androidResources {
           enable = true
       }
    }
    
    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.compose.uiTooling)
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonMain {
            kotlin.srcDir(generateDemoBuildConfig)
        }
        commonMain.dependencies {
            // Overridable so the showcase can be built against an unreleased SDK without
            // overwriting the released coordinate in the local Maven cache:
            //   ./gradlew :androidApp:assembleDebug -PheimuiCore=0.0.1-alpha-LOCAL
            implementation(
                (project.findProperty("heimuiCore") as String?)
                    ?.let { "io.heimui:heimui-core:$it" }
                    ?: libs.heimui.core
            )
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            // Real icons instead of arrows typed as text: they scale, tint and carry semantics.
            implementation(compose.materialIconsExtended)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}
