import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

/**
 * A key from `local.properties`, which is not version controlled.
 *
 * Read through the provider API rather than by opening the file, so the configuration cache
 * re-runs when the file changes instead of serving a stale value.
 */
fun localProperty(name: String): Provider<String> =
    providers.fileContents(rootProject.layout.projectDirectory.file("local.properties"))
        .asText
        .map { text -> Properties().apply { load(text.reader()) }.getProperty(name).orEmpty() }
        .filter { it.isNotBlank() }

// Where the showcase fetches its screens from.
//
// The default is GitHub Raw, so a fresh clone renders all 17 screens with no backend to stand up.
// Pointing it at a local HeimUI Studio is one line in `local.properties`, which is not version
// controlled — which is the point: nobody can commit a `localhost` that resolves only on the
// machine that wrote it, and a release build never ships one either.
//
//   sdui.baseUrl=http://10.0.2.2:8080
//
// `-PsduiBaseUrl=...` overrides it for a single build, the way `-PheimuiCore` does for the SDK.
val sduiBaseUrl: Provider<String> =
    providers.gradleProperty("sduiBaseUrl")
        .orElse(localProperty("sdui.baseUrl"))
        .orElse("https://raw.githubusercontent.com/heimui-io/heimui-demo/main/sdui")

// Which build of the SDK the showcase compiles against. Empty unless someone asked for a local
// one, in which case the coordinate carries a `-LOCAL` suffix so a failure always names the build
// it came from.
val heimuiCoreVersion: Provider<String> =
    providers.gradleProperty("heimuiCore")
        .orElse(localProperty("heimui.core.version"))

val generateDemoBuildConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/demoBuildConfig")
    val baseUrl = sduiBaseUrl
    inputs.property("sduiBaseUrl", baseUrl)
    outputs.dir(outputDir)
    doLast {
        val target = outputDir.get().file("io/heimui/demo/DemoBuildConfig.kt").asFile
        target.parentFile.mkdirs()
        target.writeText(
            """
            package io.heimui.demo

            // Generated by the `generateDemoBuildConfig` task in shared/build.gradle.kts. Do not edit.
            internal object DemoBuildConfig {
                const val SDUI_BASE_URL: String = "${baseUrl.get()}"
            }
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }
    
    android {
       namespace = "io.heimui.demo.shared"
       compileSdk = libs.versions.android.compileSdk.get().toInt()
       minSdk = libs.versions.android.minSdk.get().toInt()
    
       compilerOptions {
           jvmTarget = JvmTarget.JVM_11
       }
       androidResources {
           enable = true
       }
    }
    
    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.compose.uiTooling)
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonMain {
            kotlin.srcDir(generateDemoBuildConfig)
        }
        commonMain.dependencies {
            // Overridable so the showcase can be built against an unreleased SDK without
            // overwriting the released coordinate in the local Maven cache. Same precedence as
            // `sdui.baseUrl`: a Gradle property for one build, `local.properties` for this
            // machine, the released coordinate for everyone else.
            //
            //   ./gradlew :heimui-core:publishLocal        → 0.0.1-alpha-1-LOCAL
            //   heimui.core.version=0.0.1-alpha-1-LOCAL    in local.properties
            //
            // `mavenLocal()` is already first in settings.gradle.kts, so the local build resolves
            // without any further wiring.
            implementation(
                heimuiCoreVersion
                    .map { "io.heimui:heimui-core:$it" as Any }
                    .orElse(provider { libs.heimui.core.get() as Any })
                    .get()
            )
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            // Real icons instead of arrows typed as text: they scale, tint and carry semantics.
            implementation(compose.materialIconsExtended)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}
